sudo: required
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run migrate:test
- npm test
deploy:
#  - provider: script
#    skip_cleanup: true
#    script: ./deploy.sh
#    on:
#      all_branches: true
#      tags: true
#      repo: realfundtokens/smart-contracts
  - provider: npm
    skip_cleanup: true
    email: juanma.garrido@gmail.com
    api_key: $NPM_KEY
    on:
      all_branches: true
      tags: true
      repo: realfundtokens/realfund-smart-contracts