sudo: required
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
install:
- npm install -g truffle@beta
- npm install -g ganache-cli
- npm install
script:
- npm run lint
- npm run solium
- npm run ganache
- sleep 5
- truffle migrate --network test
- truffle test
- npm run stop
after_success:
  - npm run build #make a build folder
deploy:
#  - provider: script
#    skip_cleanup: true
#    script: ./deploy.sh
#    on:
#      all_branches: true
#      tags: true
#      repo: realfundtokens/smart-contracts
  - provider: npm
    email: juanma.garrido@gmail.com
    api_key: $NPM_KEY
    on:
      all_branches: true
      tags: true
      repo: realfundtokens/realfund-smart-contracts
