sudo: required
language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle@beta
  - npm install -g ganache-cli
  - npm install
script:
  - npm run lint
  - npm run solium
  - npm run ganache
  - sleep 5
  - truffle migrate --network test
  - truffle test
  - npm run stop
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
